### ISSUE TITLE
Add description and keyword meta tags to website

### ISSUE THREAD

**Issue by jogendra** [wxWidgets/website#17]
their is no meta tag of description and keyword. this tags are important for website and help in improving SEO.

**Comment by tierra** [comment]
I don't believe keyword tags are used at all anymore, but yes, description tags could be helpful, though our descriptions do mostly work without them:

![Google Search Results](https://user-images.githubusercontent.com/106098/37942030-661d90ca-312e-11e8-8bca-af7a555410fd.png)

Feel free to open a PR with descriptions if you want to help spend the time to fill them out. Maybe we can just focus on those pages in the screenshot since they're the ones with the most traffic and show up in results the most, and that wouldn't be too much work.
