### ISSUE TITLE
bootstrap4 presentation

### ISSUE THREAD

**Issue by doscott** [wxWidgets/website#22]
I just went through the process for using the new branch. All went well. The following error's were reported:

```
vagrant@ubuntu-xenial:/vagrant$ yarn dist
yarn run v1.5.1
$ node node_modules/npm-run-all/bin/run-p/index.js css js
$ node node_modules/npm-run-all/bin/run-s/index.js js-minify
$ node node_modules/npm-run-all/bin/run-s/index.js css-compile css-prefix css-minify
$ node_modules/node-sass/bin/node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 _assets/scss/global.scss assets/css/global.css
$ node_modules/uglify-js/bin/uglifyjs --compress --mangle --comments "/^!/" --source-map "includeSources,url=global.min.js.map" --output assets/js/global.min.js node_modules/jquery/dist/jquery.min.js node_modules/bootstrap/dist/js/bootstrap.bundle.min.js "node_modules/@fancyapps/fancybox/dist/jquery.fancybox.min.js" _assets/js/*.js
sh: 1: node_modules/uglify-js/bin/uglifyjs: Permission denied
error An unexpected error occurred: "Command failed.
Exit code: 126
Command: sh
Arguments: -c node_modules/uglify-js/bin/uglifyjs --compress --mangle --comments \"/^!/\" --source-map \"includeSources,url=global.min.js.map\" --output assets/js/global.min.js node_modules/jquery/dist/jquery.min.js node_modules/bootstrap/dist/js/bootstrap.bundle.min.js \"node_modules/@fancyapps/fancybox/dist/jquery.fancybox.min.js\" _assets/js/*.js
Directory: /vagrant
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/vagrant/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "js-minify" exited with 1.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node node_modules/npm-run-all/bin/run-s/index.js js-minify
Directory: /vagrant
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/vagrant/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error An unexpected error occurred: "Command failed.
Exit signal: SIGTERM
Command: sh
Arguments: -c node node_modules/npm-run-all/bin/run-s/index.js css-compile css-prefix css-minify
Directory: /vagrant
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/vagrant/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "js" exited with 1.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node node_modules/npm-run-all/bin/run-p/index.js css js
Directory: /vagrant
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/vagrant/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
A link to a dropbox screen shot:
https://www.dropbox.com/s/chf59kp9di16uvb/Screenshot_20180325_092320.png?dl=0

This is on a 1920x1080 monitor, latest Firefox on Tumbleweed. The title bar isn't quite right. The Quick Links area is quite different than the current in terms of looks. The layout of the main area is different as well.

It may be that things are still in a state of flux. Nothing here meant as criticism, just some feedback.

**Comment by tierra** [comment]
Yeah, things are still very much in flux. I tossed it into a branch because I knew this was going to be a big change. That said, you're already on an old commit, and I've made significant progress from what you have a screenshot of there:

![Bootstrap 4 Preview](https://user-images.githubusercontent.com/106098/37878199-7b66c3b4-3022-11e8-893d-b7e07ea2e2c7.png)

Note that in Bootstrap 4, here's some key things that changed that I've needed to update markup for:

- Navbar classes (our menu)
- Panels and wells (our sidebar and other misc content) were replaced with Cards.
- Box sizing model was completely switched to `border-box`, and a new breakpoint was added to the grid (and the xs breakpoint was renamed), so quite a bit of layout needed to be updated.
- Display property utilities were re-written, so lots of the hidden content (for smaller breakpoints) started showing up in all breakpoints (why you see two download and "learn more" buttons in the jumbotron).
- Lots of other stuff...

Anyway, I'll open up a pull request when I believe I have this in a good state for review.

I am curious about the Yarn errors though. I've tried really hard to keep this compatible with using Vagrant on Windows in VirtualBox (which doesn't support symlinks, but symlinks are very critical to how NPM and Yarn works). In fact, based on the current package set, I couldn't even get NPM 5.x to successfully install packages anymore. I did have a lot more luck with Yarn though, and I was able to `yarn --no-bin-links` along with `yarn dist` on my Vagrant environment successfully, without the use of symlinks. It's actually why I have very explicit paths to the executables under the `scripts` section, specifically so you can use those scripts with NPM packages installed using `--no-bin-links`.

Can you delete, remote update, and checkout the latest commit on the branch, destroy your Vagrant VM, try re-creating and compiling assets again? One more thing to try is to completely delete your `node_modules` folder, and re-run `yarn --no-bin-links` again for a fresh set of packages.

**Comment by doscott** [comment]
I deleted my website folder and the VM. I cloned a fresh copy and enountered the same errors. As a result I now see errors like:
```
  Server running... press ctrl-c to stop.
[2018-03-25 18:20:04] ERROR `/assets/css/global.css' not found.
[2018-03-25 18:20:04] ERROR `/assets/js/global.min.js' not found.
[2018-03-25 18:20:11] ERROR `/assets/css/global.css' not found.
[2018-03-25 18:20:11] ERROR `/assets/js/global.min.js' not found.
```
which results with even less info displayed.

Any more testing required, let me know.

**Comment by tierra** [comment]
Running `yarn dist` is what generates those files.

**Comment by tierra** [comment]
I've opened up the pull request at #23, closing this to move discussion there.
