### ISSUE TITLE
GitHub security alert

### ISSUE THREAD

**Issue by vadz** [wxWidgets/website#37]
Pushing to the repository shows an alert with [this link](https://github.com/wxWidgets/website/network/alerts).

@tierra Do we need to update our `yarn.lock` to use fixed versions of these dependencies?

**Comment by tierra** [comment]
Most are pretty unlikely to be legitimate issues, as that's mostly only a concern for server-side Node apps, but I've pushed upgrades to the majority anyway now. There's still one more advisory I didn't catch, since it'll require a major version bump that could break the site, and will need a more carefully crafted update. It's definitely not a problem with our use though.
