### ISSUE TITLE
Run failed: Publish Website - master (619621c)

### ISSUE THREAD

**Issue by doscott** [wxWidgets/website#47]
I recieved an email with this title yesterday at 7:25pm GMT-4. The body is shown below. This is from my cloned repository. I have done anything with this site other than keeping it up to date.

Run failed for master (619621c)

Repository: doscott/website
Workflow: Publish Website
Duration: 2 minutes and 18.0 seconds
Finished: 2020-05-07 22:25:15 UTC

View results
Jobs:

    publish failed (1 annotation)

It appears this workflow task is being repeated periodically on my cloned repository, and other than this occurrence (which reported Unexpected HTTP response: 403) has been successful.

I am just raising the issue in case this is not normal.

**Comment by tierra** [comment]
I did at least make sure that the "Upload" step didn't run on forks, but hadn't thought about the cron schedule triggering actions on forks too.

You can shut them off yourself on your forked repo settings:
https://github.com/doscott/website/settings/actions

I'm not sure how we can configure the action to run regular triggers, but not cron. I do like having the normal triggers working on my fork, since it verifies that it works for new changes I push up before opening a PR for merge.

**Comment by doscott** [comment]
I changed my setting. Thanks.
